## Perceptrón multicapa (MLP)

[Multilayer perceptor in scikit](https://scikit-learn.org/stable/modules/neural_networks_supervised.html)

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix
# De acuerdo a la versión scikit train_test_split puede ser
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.neural_network import MLPClassifier

conjunto_datos = pd.read_csv('sample_data/haberman - haberman.csv')

print(conjunto_datos.shape)
print (conjunto_datos.head(20))

(306, 4)
    age  year_operation  nodes_detected  over_5_years
0    30              64               1             1
1    30              62               3             1
2    30              65               0             1
3    31              59               2             1
4    31              65               4             1
5    33              58              10             1
6    33              60               0             1
7    34              59               0             2
8    34              66               9             2
9    34              58              30             1
10   34              60               1             1
11   34              61              10             1
12   34              67               7             1
13   34              60               0             1
14   35              64              13             1
15   35              63               0             1
16   36              60               1             1
17   36            

In [4]:
# Se delimitan únicamente las columnas de interés
X = conjunto_datos[['age', 'year_operation', 'nodes_detected']].values
# X_uno = conjunto_datos.iloc[:, :2]
y = conjunto_datos['over_5_years'].values.reshape(-1, 1)

# Verificación de los datos por consola
# print("Incio: ", X)
# print("Incio: ", X_uno)
# print("Incio: ",  y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.7, random_state = 0)
X_train.shape

(91, 3)

In [6]:
# TODO: normalizar los datos 
names = ['MLP logistic', 'MLP tanh', 'MLP relu', 'MLP relu / SGD/three layers']
clasificadores = [
      MLPClassifier(activation = 'logistic', max_iter = 1000),
      MLPClassifier(activation = 'tanh', max_iter = 1000),
      MLPClassifier(activation = 'relu', max_iter = 1000),
      MLPClassifier(activation = 'relu', solver = 'sgd', hidden_layer_sizes = (10, 100, 80), max_iter = 10000)]

for clasificadores, name in zip(clasificadores, names):
    print(name) 
    cv_score = cross_val_score(clasificadores, X_train, y_train, cv = 5, scoring = 'f1_weighted', n_jobs = -1)
    print(cv_score)
    print('promedio {a:5.3f}, desviación estándar {b:5.3f}'.format(a = cv_score.mean(), b = cv_score.std()))
    
#scoring parameters
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter
#https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html#sklearn.metrics.f1_score

MLP logistic
[0.69659443 0.75757576 0.75757576 0.75757576 0.75757576]
promedio 0.745, desviación estándar 0.024
MLP tanh
[0.88048246 0.75757576 0.81935484 0.66666667 0.79761905]
promedio 0.784, desviación estándar 0.071
MLP relu
[0.69659443 0.75757576 0.72916667 0.72916667 0.88888889]
promedio 0.760, desviación estándar 0.067
MLP relu / SGD/three layers
[0.69659443 0.75757576 0.72916667 0.69892473 0.72916667]
promedio 0.722, desviación estándar 0.023
